language: node_js
sudo: false
node_js:
- '10'
branches:
  only:
  - master

env:
  global:
    secure: jLozXudMr06HnRktOMxJ3T1L2jzkhf21Oz/z2f99+5Nf/P8shiw6VvQRbh2yWhZY4tIOwKRN6l+mgLQdL2nWcEoMEp9pLXq/6kuSvWFmjuxByQAXi8tkzUVnNig3uvOdRJjSpoMTJjsw9qOfL1eURYwSnQJgO7LL81IUPMnvmzgX7cqT2lFgk/bAr1Kd3Of31BCqbpxtYZROKpBT1yyUMSaNoIVOoOuJkJJFGqCPu4fURIowFJ/9EGd+VqGnHpT8JOhZ5v4HaCrNo2qpLJYJXtdXucWp16AH5gH/i3LG1EssBLhjVvNsEVLGKAphwVLZbsVe5y3STuGwDJXWKoXgdwZ8t57cC+DRKzQ2GjOg4GPOyFN9LiVyAIB1rsxjJba2byynByUZpP1rtKciGWIWUAQWT25UOAb+lsHRtCQnekYcsEve9FSKflZiGq+Nfl1mIvM9h3/3BbLgG0sDjzPUHjbKihsIjnjikypSnObSI/+dnvVk3K38tryJSwXXslPcI2xTYSQDNKX5eaa9jQYfWZUqDFRfolzCv2HBVYtcbW7evKmz7WP7nOWnW/n4nJLLSJkvqckLeQCBiO5hVb3SikaTIbiOlcXcCwIjT/yQPOi80KwEC4oDOO9RnjgSxhByjyM2CXxtP0uNJuy/AwD4dqhhujq0U2qiAPlB+Fm6O8o=

cache:
  directories:
  - node_modules

before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo-cli

before_script:
- git config --global user.name 'zhuangjinan'
- git config --global user.email zhuangjinan2018@gmail.com
- sed -i'' "s~git@github.com:FuZhouJohn/myblog.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/FuZhouJohn/myblog.git~" _config.yml
install:
- npm install

script:
- git clone https://github.com/theme-next/hexo-theme-next themes/next
- git clone https://github.com/theme-next/theme-next-fancybox themes/next/source/lib/fancybox
- npm run deploy
