language: node_js

sudo: false

node_js:
  - '8'

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_2f0f034f5258_key -iv $encrypted_2f0f034f5258_iv
  -in id_rsa.enc -out id_rsa -d
# 改变文件权限
- chmod 600 ~/.ssh/id_rsa 
# 配置 ssh
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
# 配置 git 替换为自己的信息
- git config --global user.name 'zhuangjinan'
- git config --global user.email zhuangjinan2018@gmail.com

install:
- npm install hexo-cli -g
- npm install

script:
- npm run deploy # hexo clean && hexo g -d